### ISSUE TITLE
introduce queue state?

### ISSUE THREAD

**Issue by disruptek** [shayanhabibi/loony#18]
I'd like to have some controls on the queue:

- I want to be able to pause the queue for `pop` clients (so they receive `nil`).
- I want to have a way to `clear` the entire queue, discarding the contents.
- I want a backchannel for `pop` that works while the queue is paused so that I can, for example, tear down items in the queue with extra logic.

Now, maybe the right way to implement this is with a queue manager that sits outside the queue itself, but in any event, these are pretty minor features that we should be able to support for programmer comfort.

**Comment by shayanhabibi** [comment]
1. What level of guarantee would you want with this? Every atomic read/write adds cost; I have a preliminary idea that is to have a spinlock before the pop operation begins (because we have to prevent any FAAs on the tagptrs; this would mean the threads keep cycling while they're stuck though. I could make it so they wait on a condition instead of the spin lock I guess? Haven't looked at conditions but I think there was a broadcast op).

2. Clearing the queue would be an expensive process for the thread calling it, but not for the other threads. There is again only a certain level of assurance that can be given; the calling thread can do a compare and swap to put a new head/tail on the queue -> iterate over every node and ensure they are either consumed or written (any inbetween could potentially mean another thread is still in the process of reading that item and I'm not sure how to deal with that). For each one that we find is consumed/written we take the reference contained and do a GC_unref (which would destroy it if it is the last reference). Other threads would be free to continue pushing/popping on the new head/tails

3. This really depends on how we solve 1 but should be possible either way.

**Comment by shayanhabibi** [comment]
# Clearing the queue

Writing my thoughts down on how I'm going to do this.

I begin by replacing the Tail.
0. Create a "new" node
1. Atomic load the tail of the queue.
2. Atomic load the 'next' node of the tail.
3. If the next node is nil, then we will swap it with "new", else we go back to step 1. 
4. First begin by CAS on the 'next' node. If this fails then another next has already been set. We will therefore reload that 'next' node as our tail of the queue and go back to step 2.
5. After successfully setting the 'next' node, we will do a CAS on the tail using next as expected with new node as our desired. Loop until completes (other threads will help if required).
6. Fetch and save the current tagptr of the head.
7. Perform a CAS repeatedly trying to replace the head with "new", adding +1 to the index as necessary (unless it passes the max of the slots). On success then we have assuredly given all threads a "fresh start". We now move onto elimination of the slots and their contents
8. From the Saved head tagptr, we will iterate over every slot, load their ref and deref them. at the end of the node, we access the next node atomic value and deallocate the node.
9. Check the next node ptr to see if its the same as "new". If it is, then we have cleared all the original nodes and the procedure is complete. If not, then we go back to step 8.
10. EXTA: might have to ensure health of the new nodes first slot for reasons that i cbb to explain atm
